server:
  port: 8888
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
      
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
      - id: banking
        uri: lb://BANKING-APP
        predicates:
        - Path=/banking/**
      - id: foodmenu
        uri: lb://SPRING-BATCH-DEMO
        predicates:
        - Path=/foodmenu/**
      - id: hungerbox
        uri: lb://HUNGER-BOX
        predicates:
        - Path=/hungerbox/**

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"